import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ahammed Saad- Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My page
        </h1>

        <p className={styles.description}>
          Get started by visiting my projects
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="https://ahammed-portfolio.vercel.app/" className={styles.card}>
            <h2>Portfolio</h2>
            <p>Find in-depth information about my portfolio.</p>
          </Link>

          <Link href="https://randompassword-asaad227.vercel.app/" className={styles.card}>
            <h2>Random password APP</h2>
            <p>This app generate random password which you can use where ever you like to use.</p>
          </Link>

          <Link
            href="https://github-readme-stats.vercel.app/api?username=asaad227&show_icons=true&hide_border=false&title_color=ff652f&icon_color=FFE400&bg_color=09131B&text_color=ffffff&border_color=0c1a25"
            className={styles.card}
          >
            <h2>GitHub Stats</h2>
            <p>My gitHub activities Stats.</p>
          </Link>

        
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
